Feat/#3
schoolzone06/schoolzone_backend pull request #4
Opened 2023-08-07 09:31 UTC by hw9402

- 게시물 전체 조회 기능
- 게시물 내용 조회 기능
- 게시물 등록 기능
- 게시물 업데이트 기능
- 게시물 삭제 기능

2023-08-07 10:44 UTC, NameIsUser06 commented
괜찮은거같습니다

2023-08-08 07:31 UTC, hw9402 commented
> 괜찮은거같습니다

pr 내용 수정해서 수정이랑 삭제까지 한꺼번에 머지할게요. 이렇게 나누는 게 나을 거 같아요.

2023-08-08 10:34 UTC, NameIsUser06 requested changes
카테고리랑 제목 수정 논의하고 머지합시다

2023-08-08 10:41 UTC, hw9402 commented
제목과 카테고리 둘 다 수정하도록 정했고, 그에 맞게 변경해서 푸쉬했습니다.

2023-08-09 08:41 UTC, NameIsUser06 approved these changes
코드 확인했습니다

2023-08-09 08:42 UTC, merged